### ISSUE TITLE
Avira detects application as HEUR/APC (Cloud)

### ISSUE THREAD

**Issue by TheEssem** [sauraen/seq64#1]
I tried to run the WIN64 version of the application, but instead of it launching, Avira picks it up as HEUR/APC (Cloud) and quarantines it. I tried to restore it, but that resorted in an empty file. What should I do?

**Comment by sauraen** [comment]
Well, I can assure you there's no viruses in SEQ64. You're welcome to download the source code, examine it, and build it yourself with Visual Studio 2017. The application doesn't open any network connections or register any services or startup processes, or anything else traditionally associated with malware--it doesn't even access the registry.

As far as how to get around the issue, I googled the name of this virus and it appears it is a general heuristic that has picked up false positives before. I don't know how to force your antivirus to ignore it, but that is usually a possibility. Also, if you're on Windows x64, the 32-bit application will work as well, you can try that version.

**Comment by TheEssem** [comment]
I tried to download the 32-bit version, but Chrome blocked it and said "Failed - Insufficient permissions". I'm honestly not sure what to do now, since I don't know how to set an exception with Avira.

**Comment by sauraen** [comment]
Well, thanks for letting me know, but I don't know what else to say. This isn't really an issue with SEQ64. Maybe try a different browser (i.e. Firefox), antivirus (i.e. Avast), or operating system (i.e. Linux).
