### ISSUE TITLE
Wave Race 64 romdesc not working

### ISSUE THREAD

**Issue by SportySpice** [sauraen/seq64#10]
The romdesc for Wave Race 64 (wr64_info.xml) is not working. I took a little peak inside and the file and it seems to have Mario 64 track names, so something is definitely not right here.

**Comment by sauraen** [comment]
This has been fixed--now Wave Race 64 is officially supported, with all the sequences and banks named. (The first couple banks also have tagged instruments--try exporting sequences 3 and 5--but I didn't do the rest yet. If you'd like to, I'm happy to merge the changes!)

I don't know why I ended up putting up a broken one--I thought I had gotten it working for exporting sequences in the past, but the RomDesc was obviously incorrect as you said.
