### ISSUE TITLE
Support for Mario Party

### ISSUE THREAD

**Issue by brubsby** [sauraen/seq64#16]
Hi, not sure if you're taking requests for romdesc files (or if you'd like help creating them). But I wanted to edit some midis/soundfonts for Mario Party, and it doesn't seem like there's an easy way for it to be supported (or a guide telling me how to create my own romdesc files). Is this possible?

**Comment by sauraen** [comment]
I have no idea if Mario Party uses Audioseq format! If you figure that out for sure one way or the other, that would be very helpful. And of course, I would love help with it. You mainly would copy an existing romdesc, either SM64 or OoT, and change the addresses of the relevant files. There probably won't be too many other changes to the format, e.g. the differences between SM64, SF64, and F-Zero X are minor and only in technical commands which aren't relevant to normal music sequences. However, OoT and Yoshi's Story use a version of the format with more differences.

There's a new version of SEQ64 in the works which hopefully will come out in the next month or two, which handles sequences very differently from the current version overall, but the romdesc format stuff and the actual MIDI I/O is basically the same. So any work done now could transfer over easily.

**Comment by casinograveyard** [comment]
Do you have any chance the F-Zero X romdesc?

**Comment by sauraen** [comment]
No, but F-Zero X should work with the Star Fox 64 ABI definition in SEQ64 V2.0, which is coming very soon.

**Comment by sauraen** [comment]
Very soon happened! Please try the Star Fox 64 ABI on F-Zero X and let me know what happens.
