### ISSUE TITLE
Pitch bends are a bit too extreme.

### ISSUE THREAD

**Issue by PablosCorner** [sauraen/seq64#2]
Hey there! My name is Pablo and I just wanted to report an issue where the pitch bend in this song I imported was a bit too extreme than what you would hear in the original MIDI. Hope you could take a listen.

[YouTube Video](https://www.youtube.com/watch?v=2I6_8HRY5_M)

**Comment by sauraen** [comment]
SEQ64 doesn't modify pitch bend commands when converting them to and from Audioseq. Unfortunately, the default pitch bend range for General MIDI is +/-2, whereas for many N64 games it appears to usually be +/-6. SEQ64 does support overriding the pitch bend range on export, but this doesn't change the individual commands, it simply adds MIDI RPN commands to tell your synth what the range should be. If the pitch bends in your song are not correct, simply edit the MIDI in your favorite DAW (I recommend Reaper) and modify the pitch bend commands.

**Comment by PablosCorner** [comment]
Hey! So after all this time, I finally figured out how to get around this issue. I use Sekaiju to do this, so what I found out is that if you leave only 5% of all the pitch bend data, it corrects the issue in-game, so the pitch bends don't sound out of whack. I guess the issue truly is closed now, lol.

**Comment by sauraen** [comment]
You mean turn down each pitch bend to 5% of its value, or delete 95% of the pitch bend commands?

**Comment by PablosCorner** [comment]
Turning down each one to 5% of it's original value, pretty much.

**Comment by sauraen** [comment]
Well, that's what I suggested you do! :)
