### ISSUE TITLE
GUI is way too tall for smaller displays

### ISSUE THREAD

**Issue by TorutheRedFox** [sauraen/seq64#22]

**Comment by sauraen** [comment]
SEQ64 V2.0 is 800 pixels tall plus any OS-specific title bar. This should fit on even smaller laptop displays which tend to be at least about 850 px tall or so. I can only see it being an issue on 720p displays, though these are pretty rare nowadays. 1080p is the minimum resolution for modern PC gaming.

**Comment by TorutheRedFox** [comment]
I use an 800px tall display and it's too tall there (obviously)

maybe add scrolling support for when the window is shorter than 800px?

**Comment by sauraen** [comment]
@ToruTheRedFox I have reduced SEQ64's height to 720 pixels. Hopefully it will fit on your screen now.

**Comment by TorutheRedFox** [comment]
thanks
