### ISSUE TITLE
better support for weird sequences such as the SM64 title theme with its game over variant and stuff

### ISSUE THREAD

**Issue by TorutheRedFox** [sauraen/seq64#23]
or how do I work with it?

**Comment by sauraen** [comment]
The SM64 title theme matches on .aseq -> .mus -> .aseq in SEQ64 V2.0, so it is fully supported. What do you mean by better support? Are you talking about MIDI export or import?

**Comment by TorutheRedFox** [comment]
yeah midi export and import
it only exports the game over variant of the intro, and I'd like it to export the three contained sequences (game over intro, regular intro and main loop) into separate MIDIs for editing and then reimport them into their correct locations

**Comment by sauraen** [comment]
The two different intros and the main part of the sequence are different sections of the same sequence, which is supported by SEQ64. The MIDI should have the game over intro, and then the normal intro, and then the loop. This is how it would have been made by Koji Kondo. After it was converted to MML text, they would have manually added in the MML "programming" commands to conditionally jump to the appropriate intro sections. This is all fully supported in SEQ64.

Having separate sections of a sequence converted into different MIDIs is not generally useful for other sequences besides this one, and automatically creating the commands to jump to the different intros is not really possible to do in a way that's useful across a variety of sequences.
