### ISSUE TITLE
Change Sound Bank on new interface?

### ISSUE THREAD

**Issue by LadyCookie** [sauraen/seq64#26]
Hi,
I'm new to seq64 (windows) and I've created a little midi file.
I can't find how I can change the sound bank for the sequence.

When importing into my rom, NLST 37 is used but I want to use NLST 12.

(https://user-images.githubusercontent.com/32516903/199511645-c73faa22-f7f8-45ff-b534-ca9492e0da19.png)
Wiki doesn't match with the UI (see picture). Could you help me please ?

**Comment by sauraen** [comment]
SEQ64 V2 converts sequences between MIDI, text-based assembly, and binary. It does not edit other sequence-related data in a ROM like the bank(s) for each sequence.

If the project you're contributing to uses the decomp (SM64 or OoT), there are text-based files generated by the decomp which include the bank(s) for each sequence. The fact that the data is stored separately nowadays is why SEQ64 V2 doesn't include that editing feature anymore--it only makes sense to edit that if you're working on a full ROM. Consult your romhack lead programmer for more information.

If you just want to mod a single song into a whole ROM, you can use SEQ64 V1.5 for the bank editing. You can either import the MIDI directly in SEQ64 V1.5, or you can convert the sequence from MIDI to binary in V2 and then "Load Raw" the binary in V1.5.
