### ISSUE TITLE
Request: Add support for bcseq

### ISSUE THREAD

**Issue by Kewlan** [sauraen/seq64#27]
Hi! I'm from the OoT3D Randomizer community and have been looking into what it'd take to add custom music. 
OoT3D still uses sequences, which is now in the `bcseq` format. I'm hoping it's similar enough to the other formats that seq64 would be able to at least export to it. That alone would be wonderful!

I don't know much about this stuff myself, but here's some documentation about it by the Citric Composer devs:
https://gota7.github.io/Citric-Composer/specs/seq.html
https://gota7.github.io/Citric-Composer/specs/common.html

**Comment by sauraen** [comment]
It is likely a later version of Music Macro Language, and at least theoretically I'm interested in adding support for later MML variants (Wind Waker, Twilight Princess, etc.). Unfortunately, the documentation of the sequence format on that page is very incomplete (the link is broken, but I found the actual file, but they only have two commands documented). Some of the later MML formats have appeared in their entirety in leaked data, such as the DS development kit, but I haven't looked into those.

So basically, there'd need to be a reasonably complete doc on the format (or something equivalent like decompiled code), and then also I'd need time to devote to this, which I won't have in the near future. There is a big feature which needs to be finished in seq64 (synchronization with the decomp MML assembly format), and this has been on hold for some development I've been doing in fast64.

If you would like to work on getting documentation together yourself, please let me know and I can guide you on that.

**Comment by Kewlan** [comment]
Hmm, would source code that's able to handle this file type count as documentation? There's [Citric Composer](https://github.com/Gota7/Citric-Composer) that can interpret and swap the sequences, and [SequenceConvert](https://github.com/Gota7/SequenceConvert) that can turn them into readable text (and then back to bcseq), like this:
<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/5352197/210857369-79df8d53-ac6c-4fcc-bdc3-eaa7cb48a95c.png)

</details>

**Comment by sauraen** [comment]
That is canonical Music Macro Language syntax. It looks like that was probably from the leaked DS development software. A lot of the changes compared to the N64 MML could be accomplished just by changing the definition of MML through the GUI in SEQ64. However, there are likely to be some structural incompatibilities and other things which would require code changes. Unfortunately, this is not something I will have time to work on in the near future.
