### ISSUE TITLE
Import failed, .aseq from Ocarina of Time (US 1.2)

### ISSUE THREAD

**Issue by guighub** [sauraen/seq64#28]
I tried to import my audio sequence file from OOT and it starts importing for a couple seconds and then fails with this in the debug output:
![image](https://user-images.githubusercontent.com/74810584/234737717-5b059ca1-33c0-41e2-84c9-78aa9a126167.png)

**Comment by sauraen** [comment]
It looks like you're trying to import sequence 0, the SFX sequence. This sequence contains bugs such that its structure is actually technically invalid, so SEQ64's semantic analysis of it fails. The import process would consist of manually fixing those bugs in the binary, importing, and then re-creating the bugs in the mus assembly. Fortunately, I already did this, the assembly version of it is here: https://drive.google.com/file/d/1LrJF5K7wX5L1qgI8jMBPBx0smUuUqr13/view?usp=share_link
