### ISSUE TITLE
[Question] How do you set up custom start/end loops?

### ISSUE THREAD

**Issue by PablosCorner** [sauraen/seq64#3]
So I've been trying to figure out how to set custom start and end loops, so I can skip the intro of a song when it loops again. There doesn't seem to be a straightforward way of doing it (afaik).

A friend of mine who's also been trying to figure out told me to tell/suggest this.

> "Make midi event 111 into auto detect for midi looping, with event 111 set to 0 for loop start and event 111 set to 1 for loop end."

 He's been trying to do it in FL Studio.

**Comment by LuigiXHero** [comment]
[smb11.zip](https://github.com/sauraen/seq64/files/1389422/smb11.zip)
I've been trying to figure out what a midi is auto-detecting as midi loop start and end but having no luck (midi is included) the midi loop start and end appears all throughout this midi in seq64 but I can't tell what events they are using any editors I tried.

**Comment by sauraen** [comment]
I wrote a Wiki page to answer your question. The short answer is, getting your sequence to loop has nothing to do with the Loop Start and Loop End commands. 
https://github.com/sauraen/seq64/wiki/Looping
