### ISSUE TITLE
How to select a specifc audio bank?

### ISSUE THREAD

**Issue by ThePlayerRolo** [sauraen/seq64#33]
Can you choose your audio bank  like NLST 5 instead of NLST 17 for example?

**Comment by sauraen** [comment]
The information saying which bank to use is not part of the sequence file, it is in a separate table in the ROM. Are you doing SM64? Are you using the decomp or editing the ROM directly with various tools?

**Comment by ThePlayerRolo** [comment]
nevermind, I figured SM64CoopDX, (the thing I'm using the .m64 files for) has a in its lua function to replace audio (modding is via Lua) has a bank parameter. Sorry for the confusion!
