### ISSUE TITLE
ANother question.

### ISSUE THREAD

**Issue by ThePlayerRolo** [sauraen/seq64#36]
How can I increase the amount of notes at once allowed  by Seq64? Becuase now I'm using HackerSM64 and increased the amount of notes at once even more than its normal increase, but Idk how to tell Seq64 that. Is it in the ABI?

**Comment by ThePlayerRolo** [comment]
![image](https://github.com/user-attachments/assets/6ebb956b-7e87-4b89-8084-59d08efaf871)
screen shot:

**Comment by sauraen** [comment]
This is not supported in SEQ64. SEQ64 was created at a time when this kind of change to a game's audio engine would have been impossible. Plus, that means the music file stops being a standard format.

I would suggest reverting any changes to the audio engine, and making another channel with the same instruments for the extra notes. If your arranger is experienced with N64 music, they will already do this for things like piano and strings which often use more than 4 notes at a time.
