### ISSUE TITLE
Weird sequence.

### ISSUE THREAD

**Issue by LuigiBlood** [sauraen/seq64#6]
Using this XML file for Mario Artist Polygon Studio (64DD Disk file, not the cartridge port)
https://gist.github.com/LuigiBlood/8a0a59e416cc2c2210650ba531436727

It was taken from F-Zero X Expansion Kit as a base, while the MIDIs sound okay for the most part, there's one sequence in particular that Seq64 has real issues with, that is Sequence 0x10.
This one seems to be made of several sub-sequences that are triggered over time and simply cannot export as MIDI.

**Comment by sauraen** [comment]
Audioseq is a much more powerful format than MIDI, supporting all kinds of dynamic and reactive features like that. There may be sequences which use too many of those features to be exported as MIDI. (E.g. the master Hyrule Field sequence from OoT is simply a program written in the Audioseq format, it doesn't contain any music at all, it calls other sequences which you can export.) If you're really intent on getting out the music you can edit pieces of the sequence in the editor to try to isolate sections, and export them individually. But a general solution isn't possible.
